#!/bin/sh
. /etc/init.d/rc.lib
. /etc/rc.conf

echo "${YELLOW}Welcome to Linux!${RESET}"
log_info "Linux Kernel Version:$(uname -r)"

log_info "Boot stage completed in $(cat /proc/uptime|cut -d ' ' -f 1)s"

log "Starting Services..."
for i in $SERVICES;do
    /var/services/${i} start
done

log_info "Boot completed in $(cat /proc/uptime|cut -d ' ' -f 1)s"
