#!/bin/sh
. /etc/init.d/rc.lib
ip addr add $ip/$mask dev $interface
[ "$router" ]&&ip route add default via $router dev $interface
if [ "$ip" ]; then
    log "DHCP configuration for device $interface"
    log "IP: $ip"
    log "mask: $mask"
    log "router: $router"
fi
