#!/bin/sh
. /etc/init.d/rc.lib

case "${1}" in
    start)
        log "Installing Core Packages..."
        for i in $(cat /etc/pkglist_core);do
        	pkg install "${i}"
        done
        log "Installing Packages..."
        for i in $(cat /etc/pkglist);do
        	pkg install "${i}"
        done
        ;;
esac
