#!/bin/busybox sh
RESET=$(printf "\033[0m")
RED=$(printf "\033[91m")
YELLOW=$(printf "\033[93m")
GREEN=$(printf "\033[92m")
CYAN=$(printf "\033[96m")
BLUE=$(printf "\033[94m")
MAGENTA=$(printf "\033[95m")
WHITE=$(printf "\033[97m")
decompress(){
    case "${1}" in
        *.tbz|*.bz2) bzip2 -d ;;
        *.lz)        lzip -dc ;;
        *.tar)       cat      ;;
        *.tgz|*.gz)  gzip -d  ;;
        *.xz|*.txz)  xz -dc   ;;
    esac<"${1}"
}
log(){
    echo "${WHITE}${1}${RESET}"
}
log_info(){
    echo "${CYAN}${1}${RESET}"
}

busybox dmesg -n 1
log "Installing Busybox..."
for i in $(busybox --list);do
    busybox ln -s busybox /bin/$i
done

log "Mounting tmpfs..."
mount -t tmpfs -o defaults,size=512M tmpfs /mnt/tmpfs
log "Mounting pseudo filesystems..."
mkdir /mnt/tmpfs/dev
mkdir /mnt/tmpfs/proc
mkdir /mnt/tmpfs/sys
mount -t devtmpfs dev /mnt/tmpfs/dev
mount -t proc proc /mnt/tmpfs/proc
mount -t sysfs sys /mnt/tmpfs/sys
mkdir /mnt/tmpfs/dev/pts
mkdir /mnt/tmpfs/dev/shm
mount -t devpts devpts /mnt/tmpfs/dev/pts
mount -t tmpfs tmpfs /mnt/tmpfs/dev/shm -o rw
ln -s /proc/self/fd /mnt/tmpfs/dev/fd
ln -s fd/0 /mnt/tmpfs/dev/stdin
ln -s fd/1 /mnt/tmpfs/dev/stdout
ln -s fd/2 /mnt/tmpfs/dev/stderr
mount --bind /mnt/tmpfs/dev /dev
mount --bind /mnt/tmpfs/proc /proc
mount --bind /mnt/tmpfs/sys /sys

log "Installing packages to new root..."
cd /mnt/tmpfs
printf "${MAGENTA}"
for i in $(cat /etc/pkglist_core);do
    decompress /var/packages/${i}.tar.*>/tmp/${i}.tar
    tar -xf /tmp/${i}.tar
    printf "$i "
done
for i in $(cat /etc/pkglist);do
    {
        decompress /var/packages/${i}.tar.*>/tmp/${i}.tar
        tar -xf /tmp/${i}.tar
        printf "$i "
    } &
done
wait
printf "${RESET}"
echo

log "initramfs stage completed in $(cat /proc/uptime|cut -d ' ' -f 1)s"

log_info "Switching root..."
exec switch_root /mnt/tmpfs /bin/busybox init
