#!/bin/busybox sh
decompress(){
    case "${1}" in
        *.tbz|*.bz2) bzip2 -d ;;
        *.lz)        lzip -dc ;;
        *.tar)       cat      ;;
        *.tgz|*.gz)  gzip -d  ;;
        *.xz|*.txz)  xz -dc   ;;
    esac<"${1}"
}

busybox dmesg -n 1
echo "Installing Busybox..."
for i in $(busybox --list);do
    busybox ln -s busybox /bin/$i
done

echo "Mounting tmpfs..."
mount -t tmpfs -o defaults,size=512M tmpfs /mnt/tmpfs
echo "Mounting pseudo filesystems..."
mkdir /mnt/tmpfs/dev
mkdir /mnt/tmpfs/proc
mkdir /mnt/tmpfs/sys
mount -t devtmpfs dev /mnt/tmpfs/dev
mount -t proc proc /mnt/tmpfs/proc
mount -t sysfs sys /mnt/tmpfs/sys
mkdir /mnt/tmpfs/dev/pts
mkdir /mnt/tmpfs/dev/shm
mount -t devpts devpts /mnt/tmpfs/dev/pts
mount -t tmpfs tmpfs /mnt/tmpfs/dev/shm -o rw
ln -s /proc/self/fd /mnt/tmpfs/dev/fd
ln -s fd/0 /mnt/tmpfs/dev/stdin
ln -s fd/1 /mnt/tmpfs/dev/stdout
ln -s fd/2 /mnt/tmpfs/dev/stderr
mount --bind /mnt/tmpfs/dev /dev
mount --bind /mnt/tmpfs/proc /proc
mount --bind /mnt/tmpfs/sys /sys

echo "Installing packages to new root..."
cd /mnt/tmpfs
for i in $(cat /etc/pkglist_core);do
    decompress /var/packages/${i}.tar.*>/tmp/${i}.tar
    tar -xf /tmp/${i}.tar
    echo "$i done"
done
for i in $(cat /etc/pkglist);do
    {
        decompress /var/packages/${i}.tar.*>/tmp/${i}.tar
        tar -xf /tmp/${i}.tar
        echo "$i done"
    } &
done
wait

echo "initramfs stage completed in $(cat /proc/uptime|cut -d ' ' -f 1)s"

echo "Switching root..."
exec switch_root /mnt/tmpfs /bin/busybox init
