#!/bin/busybox sh
decompress(){
    case "${1}" in
        *.tbz|*.bz2) bzip2 -d ;;
        *.lz)        lzip -dc ;;
        *.tar)       cat      ;;
        *.tgz|*.gz)  gzip -d  ;;
        *.xz|*.txz)  xz -dc   ;;
    esac<"${1}"
}

echo "Installing Busybox..."
for i in $(busybox --list);do
    busybox ln -s busybox /bin/$i
done

echo "Mounting pseudo filesystems..."
mount -t devtmpfs dev /dev
mount -t proc proc /proc
mount -t sysfs sys /sys
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /dev/shm -o rw
ln -s /proc/self/fd /dev/fd
ln -s fd/0 /dev/stdin
ln -s fd/1 /dev/stdout
ln -s fd/2 /dev/stderr

echo "Mounting tmpfs..."
mount -t tmpfs -o defaults,size=512M tmpfs /mnt/tmpfs

echo "Installing packages to new root..."
cd /mnt/tmpfs
for i in $(cat /etc/pkglist_core);do
    decompress /var/packages/${i}.tar.*>/tmp/${i}.tar
    tar -xf /tmp/${i}.tar
    echo "$i done"
done
for i in $(cat /etc/pkglist);do
    {
        decompress /var/packages/${i}.tar.*>/tmp/${i}.tar
        tar -xf /tmp/${i}.tar
        echo "$i done"
    } &
done
wait

echo "initramfs stage completed in $(cat /proc/uptime|cut -d ' ' -f 1)s"

echo "Switching root..."
exec switch_root /mnt/tmpfs /bin/busybox init

