name: Compile Linux Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Compile Kernel
      run: |
        KERNEL_VERSION=6.6.39
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
        tar -xf linux-${KERNEL_VERSION}.tar.xz
        pushd linux-${KERNEL_VERSION}
        make defconfig
        make -j$(nproc)
        cp arch/x86/bzImage ../vmlinuz
        popd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vmlinuz
        path: vmlinuz
